version: "2"

services:
  mongo:
    image: mongo:4.0
    container_name: clinic-db
    volumes:
      - "data_koaapi:/data/db"
    ports:
      - "27017:27017"
    command: --smallfiles

  backend:
    build:
      context: ./backend
    container_name: clinic-backend
    ports:
      - "3001:3001"
    links:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/clinic
volumes:
  data_koaapi:
