version: "3.3"
services: 
  mongo:
    image: mongo:4.0
    restart: always
    container_name: mongodb
    volumes:
      - "data:/data/db"
    ports:
      - "27017:27017"
    command: --smallfiles
    networks:
      - clinic
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    links:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/clinic
    networks:
      - clinic
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    links:
      - backend
    environment:
      - NODE_ENV=development
      - MONGODB_URI=http://backend:3001/
    networks:
      - clinic
volumes:
  data:

networks:
  clinic:
